apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sample-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: An operator for QE testing
  displayName: Sample Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sample
  - nginx
  links:
  - name: Sample Operator
    url: https://sample-operator.domain
  maintainers:
  - email: jiazha@redhat.com
    name: JianZhang
  maturity: alpha
  provider:
    name: Jian
  version: 0.0.0
